WIP: Added a separate test for retrieving the median of pet ages.
eclipse/eclipse-collections-kata pull request #168
Opened 2020-12-27 11:11 UTC by mydeveloperplanet

Added a test for retrieving the median of the pet ages. The solution was already in exercise 4, but it was not yet contained in the exercise itself. Created a separate test for it as suggested in https://github.com/eclipse/eclipse-collections-kata/pull/166

I did not yet update the documentation, first wanted to verify whether the test looks ok.

2020-12-29 19:26 UTC, prathasirisha requested changes
Hi @mydeveloperplanet, thank you for your contribution! Changes look great. 

Can you please rebase your fork(I see you are a couple of commits behind) and also squash your commits into one?

2020-12-30 10:47 UTC, mydeveloperplanet commented
I messed things up now. Did the rebase and squash commit, it looked ok in my local repo, but something went wrong during the push. I will try to fix it later today.

2020-12-30 13:48 UTC, mydeveloperplanet commented
Fixed it, forgot to **force** push :-s
It should be ok now

2020-12-30 21:15 UTC, prathasirisha commented
Thank you @mydeveloperplanet for your contribution and rebasing/squashing commits into one! 👍

2020-12-30 21:16 UTC, prathasirisha approved these changes
LGTM

2020-12-30 21:17 UTC, merged