Clean up solutions for Exercise 3 of Pet Kata.
eclipse/eclipse-collections-kata pull request #179
Opened 2021-04-24 21:46 UTC by donraab

Signed-off-by: Donald Raab <Donald.Raab@bnymellon.com>

2021-04-24 23:39 UTC, prathasirisha requested changes
LGTM, @donraab can you please update copyright information?

2021-04-24 23:59 UTC, nikhilnanivadekar commented
I think we should do a similar exercise like the main project to update all
copyright years. Happy to raise a PR if needed.

On Sat, Apr 24, 2021 at 5:39 PM Sirisha Pratha ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> LGTM, @donraab <https://github.com/donraab> can you please update
> copyright information?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipse/eclipse-collections-kata/pull/179#pullrequestreview-644075008>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACLY4XKTR7ATN4X6JNG2MXTTKNJCJANCNFSM43QRTBZQ>
> .
>

2021-04-25 00:16 UTC, prathasirisha commented
Good point @nikhilnanivadekar. Will definitely help with future contributions. Please raise a PR, I will be happy to review and merge.

2021-04-25 00:21 UTC, prathasirisha approved these changes

2021-04-25 00:22 UTC, merged