Fix for issue 188: Updated POM, confirmed that M3 is getting pulled i…
eclipse/eclipse-collections-kata pull request #189
Opened 2021-09-02 11:51 UTC by RamVaidya

Fix for issue 188: Updated POM, confirmed that M3 is getting pulled in and used during the build. Also confirmed that the solutions still work as expected.

2021-09-02 15:12 UTC, prathasirisha requested changes
Hi @RamVaidya thank you for your contribution. 

Please remove all files except pom.xml from this commit. These .idea/ files are not meant to be committed with each contribution. You should only have one file (pom.xml) in this commit. 

Also, since I know you are intending to work on Eclipse Collections, would like to share the commit message [guidelines. 
](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#commit-messages).  Hope this helps!

2021-09-03 00:58 UTC, RamVaidya commented
@prathasirisha Updated the pull request with revert & new push with just the POM changes.

2021-09-03 01:42 UTC, prathasirisha commented
Thank you @RamVaidya. Changes look good.

Could you please squash all your commits to one?

2021-09-03 11:12 UTC, RamVaidya commented
@prathasirisha ... I don't know if I did the right thing here .. I did rebase -i HEAD~3 followed by squash/edit/commit/push and now I have 5 commits instead of one.
It may be a UI issue and the commits are indeed squashed, or may be I just did a missive No-op.
Could you please check when you get some time.

Thanx.

2021-09-03 12:26 UTC, nikhilnanivadekar commented
You need to update your local first.

git fetch —all

it should pull upstream and origin.

After that do:
git rebase -i upstream/master

Using the editor squash the commits, the editor will explain what tags to use.

After it’s squashed do this:

git push -f

Hope that helps

2021-09-03 15:11 UTC, RamVaidya commented
@nikhilnanivadekar  & @prathasirisha 
Thanx for your comments, I'm still stuck and clearly doing something wrong.
I'll read up the documents a little more and try to squash the commits - the content is fine, but somehow the squash isn't working. I tried using the GUI as well to no avail, so it isn't the commands it is the way I see git workflow (or don't see).

2021-09-03 15:46 UTC, RamVaidya commented
@nikhilnanivadekar & @prathasirisha 
Thanx for your help.
Sirisha was able to help me fix the issues, we now have a squashed commit in the pull request.

2021-09-03 15:48 UTC, prathasirisha approved these changes

2021-09-03 16:06 UTC, prathasirisha approved these changes

2021-09-03 16:07 UTC, merged