Add support for JDK17 and JDK11 builds and add new jdk17 parent pom
eclipse/eclipse-collections-kata pull request #267
Opened 2023-02-24 16:29 UTC by rosebernardsha

Add support for JDK17 and JDK11 modules to be built separately
Add new jdk17 parent pom to separate 17 builds
Easy to clean up later when upgraded to 17
Upgrade workflow versions to use the new node16 runners
Add workflow changes for 17 modules cascade call 11 modules
Add mock 17 feature record class and unit tests to test 17 builds
Test workflows in fork

2023-03-02 22:29 UTC, donraab requested changes
Hi @rosebernardsha, this looks really good, thank you! This will allow us to start adding JDK 17 modules to the kata to take advantage of and test out new language features with Eclipse Collections. I have a couple of minor changes requested inline.

2023-03-02 22:29 UTC, donraab commented on record-kata/src/test/java/org/eclipse/collections/recordkata/RecordTest.java
> +        var zuluJava11BuildName = this.openJdkDistribution.get(0).buildName();
This could be `getFirst()` instead of `get(0)`

2023-03-02 22:29 UTC, donraab commented on record-kata/src/test/java/org/eclipse/collections/recordkata/RecordSetup.java
> +
Remove the extra blank line.

2023-03-02 22:29 UTC, donraab commented on record-kata-solutions/src/test/java/org/eclipse/collections/recordkata/RecordSetup.java
> +
Remove the extra blank line.

2023-03-03 22:45 UTC, donraab approved these changes
LGTM. Thanks for the contribution @rosebernardsha !

2023-03-04 03:25 UTC, merged

2023-03-06 20:32 UTC, rosebernardsha commented
> LGTM. Thanks for the contribution @rosebernardsha !

Thanks for the review Don!