Add enhancement #287: TextProcessorEC.distinctLetters() for haiku-kata-solutions
eclipse/eclipse-collections-kata pull request #333
Opened 2023-09-22 21:23 UTC by anmbajaj

Add enhancement #287: TextProcessorEC.distinctLetters() for haiku-kata-solutions

2023-09-22 21:27 UTC, rachanavishwanath approved these changes
LGTM

2023-09-22 21:32 UTC, rachanavishwanath approved these changes

2023-09-22 21:35 UTC, rzrobin213 approved these changes

2023-09-22 22:21 UTC, rzrobin213 requested changes

2023-09-22 22:21 UTC, rzrobin213 commented on haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorEC.java
> +                .toBag()
this is unnecessary

2024-09-05 16:09 UTC, prathasirisha commented
Closing this PR, please re-open it if you are interested in working on this issue.

2024-09-05 16:09 UTC, closed without merging